apiVersion: v1
kind: Service
metadata:
  labels:
    app: openunison
  name: openunison
  namespace: openunison
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
    name: openunison-secure
  - port: 80
    protocol: TCP
    targetPort: 8080
    name: openunison-insecure
  selector:
    app: openunison
  sessionAffinity: ClientIP
  type: NodePort
status:
  loadBalancer: {}
